### ISSUE TITLE
Issue with .to_callable() function

### ISSUE THREAD

**Issue by budprat** [Open-EO/openeo-pg-parser-networkx#25]
Environment : Ubuntu 22.04, Python 3.10

Using openeo-pg-parser-networkx library function from the Example in  [https://github.com/Open-EO/openeo-pg-parser-networkx/blob/main/examples/01_minibackend_demo.ipynb]() ,  I am having below error while executing the Process graph, Process graph used is [https://github.com/Open-EO/openeo-pg-parser-networkx/blob/main/tests/data/graphs/load_save.json[()

>>> pg_callable = parsed_graph.to_callable(process_registry=process_registry)
>>> pg_callable()

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/openeo_pg_parser_networkx/graph.py", line 371, in node_callable
    result = prebaked_process_impl(
TypeError: save_result() got an unexpected keyword argument 'named_parameters'

**Comment by LukeWeidenwalker** [comment]
Hi @budprat - thanks for reporting this! This part of the example notebook was indeed broken, because of upstream changes to openeo-processes-dask and the introduction of the wrap_funcs functionality in the `ProcessRegistry` - I have updated the example notebook to reflect this!
