### ISSUE TITLE
matplotlib dependency

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-pg-parser-networkx#29]
matplotlib and it's dependencies is installed when installing the parser. However, it's used only for plotting the graph/nodes.
Can we make this dependency optional?
https://github.com/Open-EO/openeo-pg-parser-networkx/blob/03e8bc3df414cfe4e16fe72da39c397d409ec114/openeo_pg_parser_networkx/graph.py#L456

**Comment by LukeWeidenwalker** [comment]
Hmm, I think unfortunately, we won't be able to drop this easily, as `matplotlib` is a core dependency of networkx: https://github.com/networkx/networkx/blob/main/requirements/default.txt

I suppose we could open an issue over there and see whether they'd be open to making this optional, but for the time being I think we're stuck with this!

**Comment by LukeWeidenwalker** [comment]
I've opened https://github.com/networkx/networkx/issues/6469
