### ISSUE TITLE
UPD support

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-pg-parser-networkx#47]
After a talk with @m-mohr, we were wondering if this parser is able to handle UDP like the ones available here:
https://github.com/Open-EO/openeo-community-examples/blob/main/processes/

@LukeWeidenwalker did you ever try to parse a UPD process graph?

**Comment by m-mohr** [comment]
The full idea is that you for example send https://github.com/Open-EO/openeo-community-examples/blob/main/processes/array_find_nodata.json to /process_graphs and then use can use array_find_nodata in a new process that references "array_find_nodata" as id and uses "user" as namespace. The namespace indicates that it's a process coming from /process_graphs.

**Comment by LukeWeidenwalker** [comment]
> After a talk with @m-mohr, we were wondering if this parser is able to handle UDP like the ones available here: https://github.com/Open-EO/openeo-community-examples/blob/main/processes/
> 
> @LukeWeidenwalker did you ever try to parse a UPD process graph?

I did consider UDP support while initially writing this, so this should be doable, but haven't tried it. I agree with Matthias, the parsing itself should be fairly straight-forward. The bigger (but also feasible) change would be to populate the process registry with available UDPs before starting execution and making sure that the UDP nodes get expanded into their full process graphs (I think this wants to be handled at parse-time, not during execution).
