### ISSUE TITLE
logging instead of print

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-pg-parser-networkx#49]
Similarly to the logging improvements done for openeo-processes-dask here: https://github.com/Open-EO/openeo-processes-dask/pull/128
I think we should also do the same for this project, since using print is not ideal:
https://github.com/Open-EO/openeo-pg-parser-networkx/blob/bf8be1e6d574d875b13f378495f372ed7b8a5a29/openeo_pg_parser_networkx/graph.py#L221

**Comment by LukeWeidenwalker** [comment]
Good idea!
