### ISSUE TITLE
BoundingBox doesn't support EPSG codes

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-pg-parser-networkx#78]
Bounding boxes can have integer EPSG codes as crs. This is not supported by the BoundingBox class as far as I can tell. It returns:
> 'int' object has no attribute 'strip'

Example:
```
extent = {
  "east": 7.615929556794445,
  "south": 51.95982196234872,
  "west": 7.615340662408175,
  "north": 51.96005351522534,
  "crs": 4326
}
bbox = BoundingBox(**extent)
```

Integer EPSG codes should be supported according to the openEO process specs.

**Comment by GeraldIr** [comment]
#79 Fixes this
