### ISSUE TITLE
Update pydantic version to v2

### ISSUE THREAD

**Issue by iacopoff** [Open-EO/openeo-pg-parser-networkx#82]
I am facing version conflicts when using `openeo-pg-parser-network` with other python libraries that depend on pydantic.

For example, [Hydromt](https://github.com/Deltares/hydromt) requires `pydantic ~=2.4`, whereas `openeo-pg-parser-network` is fixed on `pydantic = "^1.9.1"`, and they are not compatible.

Is it possible to update the pydantic version to at least v2?

**Comment by clausmichele** [comment]
I created a draft PR for this, but I need some help: https://github.com/Open-EO/openeo-pg-parser-networkx/pull/83

**Comment by clausmichele** [comment]
@iacopoff the PR has been merge, you can close this issue now!
